name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy when the main branch is pushed to

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Set up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.110.0'  # You can specify any version

      # Build the Hugo site
      - name: Build the site
        run: hugo --minify

      # Deploy the Hugo site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
